// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using gestor_cestas_api.Models;

#nullable disable

namespace gestor_cestas_api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230927200439_M00")]
    partial class M00
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.11");

            modelBuilder.Entity("gestor_cestas_api.Models.Beneficiario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apelido")
                        .HasColumnType("TEXT");

                    b.Property<string>("Bairro")
                        .HasColumnType("TEXT");

                    b.Property<string>("CPF")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cidade")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Foto")
                        .HasColumnType("BLOB");

                    b.Property<string>("Logradouro")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Numero")
                        .HasColumnType("TEXT");

                    b.Property<string>("RG")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Beneficiarios");
                });

            modelBuilder.Entity("gestor_cestas_api.Models.Dependente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CPF")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdBeneficiario")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("Parentesco")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IdBeneficiario");

                    b.ToTable("Dependentes");
                });

            modelBuilder.Entity("gestor_cestas_api.Models.LinkDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BeneficiarioId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Href")
                        .HasColumnType("TEXT");

                    b.Property<string>("Metodo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rel")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BeneficiarioId");

                    b.ToTable("LinkDto");
                });

            modelBuilder.Entity("gestor_cestas_api.Models.ListaNecessidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdBeneficiario")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ListaNecessidades")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IdBeneficiario");

                    b.ToTable("ListaNecessidades");
                });

            modelBuilder.Entity("gestor_cestas_api.Models.RegistroCesta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataEntrega")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdBeneficiario")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdVoluntario")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuantidadeCesta")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IdBeneficiario");

                    b.HasIndex("IdVoluntario");

                    b.ToTable("RegistroCesta");
                });

            modelBuilder.Entity("gestor_cestas_api.Models.Voluntario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bairro")
                        .HasColumnType("TEXT");

                    b.Property<string>("CPF")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cidade")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Logradouro")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Numero")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Voluntarios");
                });

            modelBuilder.Entity("gestor_cestas_api.Models.Dependente", b =>
                {
                    b.HasOne("gestor_cestas_api.Models.Beneficiario", "Beneficiario")
                        .WithMany("Dependente")
                        .HasForeignKey("IdBeneficiario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Beneficiario");
                });

            modelBuilder.Entity("gestor_cestas_api.Models.LinkDto", b =>
                {
                    b.HasOne("gestor_cestas_api.Models.Beneficiario", null)
                        .WithMany("Links")
                        .HasForeignKey("BeneficiarioId");
                });

            modelBuilder.Entity("gestor_cestas_api.Models.ListaNecessidade", b =>
                {
                    b.HasOne("gestor_cestas_api.Models.Beneficiario", "Beneficiario")
                        .WithMany("ListaNecessidade")
                        .HasForeignKey("IdBeneficiario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Beneficiario");
                });

            modelBuilder.Entity("gestor_cestas_api.Models.RegistroCesta", b =>
                {
                    b.HasOne("gestor_cestas_api.Models.Beneficiario", "Beneficiario")
                        .WithMany("RegistroCesta")
                        .HasForeignKey("IdBeneficiario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("gestor_cestas_api.Models.Voluntario", "Voluntario")
                        .WithMany("RegistroCesta")
                        .HasForeignKey("IdVoluntario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Beneficiario");

                    b.Navigation("Voluntario");
                });

            modelBuilder.Entity("gestor_cestas_api.Models.Beneficiario", b =>
                {
                    b.Navigation("Dependente");

                    b.Navigation("Links");

                    b.Navigation("ListaNecessidade");

                    b.Navigation("RegistroCesta");
                });

            modelBuilder.Entity("gestor_cestas_api.Models.Voluntario", b =>
                {
                    b.Navigation("RegistroCesta");
                });
#pragma warning restore 612, 618
        }
    }
}
